apiVersion: apps/v1
kind: Deployment
metadata:
 name: db-app-deployment
 labels:
  app: db-app
spec:
 replicas: 1
 selector:
  matchLabels:
   app: db-app
 template:
  metadata:
   labels:
    app: db-app
  spec:
   containers:
    - name: db-app
      image: dnakajima/inbound-app:3.0
      ports:
      - containerPort: 8080
    - name: svc-client
      image: dnakajima/netutils:1.3

---
apiVersion: v1
kind: Service
metadata:
 name: db-app-svc 
 annotations:
  ves.io/proxy-type: HTTP_PROXY
spec:
 type: ClusterIP
 ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 8080
 selector:
  app: db-app
